// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GasolinerasVIP.Models;
//
//    var transaction = Transaction.FromJson(jsonString);

namespace GasolinerasVIP.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Transaction
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("gasStationId")]
        public long GasStationId { get; set; }

        [JsonProperty("gasStation")]
        public GasStation GasStation { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("receivedOrderDate")]
        public DateTimeOffset ReceivedOrderDate { get; set; }

        [JsonProperty("deliveredOrderDate")]
        public DateTimeOffset DeliveredOrderDate { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("magnaPrice")]
        public decimal MagnaPrice { get; set; }

        [JsonProperty("orderedMagna")]
        public decimal OrderedMagna { get; set; }

        [JsonProperty("premiumPrice")]
        public decimal PremiumPrice { get; set; }

        [JsonProperty("orderedPremium")]
        public decimal OrderedPremium { get; set; }

        [JsonProperty("dieselPrice")]
        public decimal DieselPrice { get; set; }

        [JsonProperty("orderedDiesel")]
        public decimal OrderedDiesel { get; set; }

        [JsonProperty("subtotal")]
        public decimal Subtotal { get; set; }

        [JsonProperty("tax")]
        public decimal Tax { get; set; }

        [JsonProperty("serviceFee")]
        public decimal ServiceFee { get; set; }

        [JsonProperty("deliveryFee")]
        public decimal DeliveryFee { get; set; }

        [JsonProperty("disccount")]
        public decimal Disccount { get; set; }

        [JsonProperty("total")]
        public decimal Total { get; set; }
    }

   
    public partial class Transaction
    {
        public static Transaction FromJson(string json) => JsonConvert.DeserializeObject<Transaction>(json, GasolinerasVIP.Models.Converter.Settings);
    }
}
